# Generated by Django 5.0.6 on 2024-07-22 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('data', models.TextField()),
                ('win_threshold', models.IntegerField(default=0)),
            ],
        ),
    ]
