# Generated by Django 5.0.6 on 2024-07-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0002_dailydata_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='center_letter',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
