# Generated by Django 5.0.6 on 2024-07-30 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0003_dailydata_center_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
