# Generated by Django 5.0.6 on 2024-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0004_alter_dailydata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='letters',
            field=models.JSONField(default=list),
        ),
    ]
