# Generated by Django 5.0.6 on 2024-08-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0007_alter_dailydata_letters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydata',
            name='letters',
        ),
    ]
