# Generated by Django 5.0.6 on 2024-08-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0008_remove_dailydata_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='letters',
            field=models.JSONField(default=list),
        ),
    ]
