# Generated by Django 5.0.6 on 2024-08-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0009_dailydata_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
