# Generated by Django 5.0.6 on 2024-08-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_data', '0012_alter_dailydata_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='letters',
            field=models.JSONField(default=list),
        ),
    ]
