# Generated by Django 5.0.6 on 2024-07-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_player_color_bottom_player_color_top_player_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='color_bottom',
            field=models.CharField(default='#F8E7A0', max_length=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='color_top',
            field=models.CharField(default='#FFA607', max_length=7),
        ),
    ]
