# Generated by Django 5.0.6 on 2024-07-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_player_accessory_player_daily_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='daily_words',
            field=models.TextField(null=True),
        ),
    ]
