# Generated by Django 5.0.6 on 2024-08-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_player_daily_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='daily_words',
            field=models.JSONField(default=list),
        ),
    ]
