# Generated by Django 5.0.6 on 2024-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_player_infinite_center_letter_player_infinite_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='daily_words',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='player',
            name='infinite_words',
            field=models.JSONField(default=list),
        ),
    ]
